export default {
  metaTitle: "Ruben Martinez Jr. - Artist, Developer, Technologist",
  metaDescription:
    "Hi! I'm Ruben. I'm a developer, designer, and photographer, who's passionate about building cool stuff.",
  metaUrl: "https://ruben.codes/",
  metaImage: "https://ruben.codes/static/photography/landscapes/43.jpg",

  info: {
    emailAddress: "rmj@hey.com",
  },
  skills: [
    "HTML5",
    "ES6+",
    "TypeScript",
    "PWAs",
    "React",
    "React Context",
    "React Hooks",
    "React-Router",
    "React-Native",
    "Preact",
    "Redux",
    "CSS",
    "CSS Modules",
    "SCSS",
    "Tailwind",
    "Cypress",
    "Webpack",
    "Git",
    "Github",
    "Gitlab",
    "CI/CD",
    "Sketch",
    "Figma",
    "JIRA",
  ],
  links: [
    { title: "GitHub", href: "https://github.com/rubencodes" },
    { title: "LinkedIn", href: "https://linkedin.com/in/rubencodes" },
    { title: "Twitter", href: "https://twitter.com/rubencodes" },
    { title: "Resume", href: "/static/docs/resume.pdf" },
  ],
  experience: [
    {
      name: "OkCupid",
      location: "New York, New York",
      detail: "Staff Software Engineer",
      startDate: "October 2021",
      endDate: "Present",
      text: "I work on the Web Core Team, where I've spearheaded efforts to covert our codebase to TypeScript, added Cypress test coverage to our CI pipeline (and educated our team on how to write good, stable tests), and added Honeycomb tracing to our frontend and API layers for improved visibility into our system.",
    },
    {
      name: "Slack",
      location: "New York, New York",
      detail: "Senior Software Engineer",
      startDate: "April 2020",
      endDate: "October 2021",
      text: "I work on the frontend team creating insightful data visualizations for our enterprise customers.",
    },
    {
      name: "OkCupid",
      location: "New York, New York",
      detail: "Senior Software Engineer",
      startDate: "June 2018",
      endDate: "April 2020",
      text: "I worked on the web and iOS teams at OkCupid, helping come up with new and interesting ways for people to get to know each other online. I got the opportunity to work on several major projects, including reworking the web experience into a Single Page App, and rewriting OkCupid's instant messenger using React.",
    },
    {
      name: "Well Health Inc",
      location: "San Francisco, CA",
      detail: "Lead Frontend Eng",
      startDate: "September 2015",
      endDate: "June 2018",
      text: "Designed and built a HIPAA-compliant encrypted messaging progressive web app with real-time push notifications & offline support, that allows hospitals and clinics to communicate securely and reliably with their patients.",
    },
    {
      name: "All-Star Code",
      location: "New York, NY",
      detail: "Lead Instructor",
      startDate: "June 2015",
      endDate: "August 2016",
      text: "Introduced a class of 20 high school students to web & mobile app development, robotics and physical computing, while teaching them to use languages like Python, JS, and C.",
    },
    {
      name: "Apress Media",
      location: "Brunswick, ME",
      detail: "Writer",
      startDate: "February 2015",
      endDate: "June 2015",
      text: "Co-authored a book on teaching Swift development of Apple Watch apps using WatchKit 1.0.",
    },
  ],
  education: [
    {
      name: "Bowdoin College",
      location: "Brunswick, ME",
      detail: "B.A.",
      startDate: "August 2011",
      endDate: "May 2015",
      text: "Computer Science major with a Visual Arts minor.",
    },
    {
      name: "University of Texas Brownsville",
      location: "Brownsville, TX",
      detail: "A.S.",
      startDate: "August 2009",
      endDate: "May 2011",
      text: "Majored in Biology and Chemistry.",
    },
  ],
  projects: [
    {
      name: "Recal",
      detail: "React Component",
      text: "Built a ~6kb reusable React/Preact Calendar component using CSS Grid. Reached #12 on the global trending repositories on GitHub.",
    },
    {
      name: "Piggy",
      detail: "Mac App",
      text: "Developed a Mac menu bar app for viewing up-to-date cryptocurrency prices and Coinbase wallet data.",
    },
    {
      name: "Muzee",
      detail: "iOS App",
      text: "Created an iOS app for capturing photos of paintings, correcting skewed perspectives, and viewing them in AR.",
    },
    {
      name: "Avivore",
      detail: " Chrome Extension",
      text: 'Built an extension that uses Google’s Perspective API to auto-hide "toxic" tweets on Twitter.com in real time.',
    },
    {
      name: "Recloud",
      detail: "NPM Package",
      text: "Created a React mixin for memoizing results from API calls given prop or state dependencies.",
    },
    {
      name: "Archive",
      detail: "Chrome Extension",
      text: "Developed an extension that allows you to archive websites to the Wayback Machine with just a click.",
    },
    {
      name: "Flat.Style",
      detail: "JavaScript PWA",
      text: "Created an offline-ready web app for generating icons with shadow effects given any image using the HTML Canvas API.",
    },
    {
      name: "GroupCodes",
      detail: "JavaScript SPA",
      text: "Built a real-time collaborative web-based code editor aimed at students working together on projects.",
    },
    {
      name: "Infinitweet",
      detail: "Chrome Extension, iOS & Android apps",
      text: "Created a social media tool for sending “infinitely” long tweets, by converting text into images optimized for Twitter. 3.6k downloads.",
    },
    {
      name: "DUCK!",
      detail: "iOS app",
      text: "TouchID/FaceID-secured photo locker, with a responsive layout for iPhone & iPad compatibility. 3.4k downloads.",
    },
    {
      name: "LittleData",
      detail: "Chrome app",
      text: "Designed a JavaScript app that used WebAudio API and WebRTC to attempt to translate visual input into a unique, identifiable sound.",
    },
    {
      name: "Bowdoin Dining",
      detail: "JavaScript SPA, iOS & Android apps",
      text: "Developed a suite of apps for Bowdoin College Dining used by over 5.6k students and faculty.",
    },
    {
      name: "WBOR Radio",
      detail: "Chrome Extension, iOS & Android apps",
      text: "Developed apps to allow anyone to stream WBOR Radio, the Bowdoin College student radio station, from their phone or laptop. 3.8k downloads.",
    },
  ],
  art: {
    baseURL: "/static/art/",
    largePrefix: "MD/",
    thumbPrefix: "SM/",
    images: [
      "Abstract/0.jpg",
      "Abstract/1.jpg",
      "Abstract/2.jpg",
      "Abstract/5.jpg",
      "Abstract/6.jpg",
      "Abstract/7.jpg",
      "Abstract/8.jpg",
      "Abstract/9.jpg",
      "Abstract/10.jpg",
      "Abstract/11.jpg",
      "Abstract/12.jpg",
      "Abstract/13.jpg",
      "Abstract/14.jpg",
      "Abstract/15.jpg",
      "Abstract/16.jpg",
      "Abstract/17.jpg",
      "Abstract/18.jpg",
      "Abstract/19.jpg",
    ],
  },
  design: {
    baseURL: "/static/design/",
    largePrefix: "MD/",
    thumbPrefix: "SM/",
    images: [
      "WELL/NoAnalytics.jpg",
      "WELL/SleepDetected.jpg",
      "WELL/404.jpg",
      "WELL/Banner.png",
      "WELL/Cards.png",
      "WELL/Shirt.png",
      "WELL/App.png",
      "Recal/Recal.png",
      "Piggy/Piggy.png",
      "Bowdoin/Dining.png",
      "Bowdoin/WBOR.png",
      "Infinitweet/Infinitweet.png",
      "Confidant/Confidant.png",
      "GroupCodes/GroupCodes.png",
    ],
  },
} as const;
